branches:
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
bundler_args: --without development

rvm:
- 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 4.3"
    - PUPPET_GEM_VERSION="~> 4.6"
    - PUPPET_GEM_VERSION="~> 3.8"
